
service: aws-node-generic-authorizer

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 15
  region: ${opt:region}
  stage: ${opt:stage}
  profile: ${opt:profile}
  memorySize: 256
  cfLogs: true

functions:
  publicEndpoint:
    handler: handler.publicEndpoint
    events:
      - http:
          path: api/public
          method: get
          cors: true
  auth:
    handler: auth.authorize
  privateEndpoint:
    handler: handler.privateEndpoint
    events:
      - http:
          path: api/private
          method: get
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies